CREATE TABLE Movie(
id INT,
title VARCHAR(100) NOT NULL,
year INT NOT NULL,
rating VARCHAR(10),
company VARCHAR(50),
CHECK(id > 0 && id <= MaxMovieID(id)),
PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE Actor(
id INT,
last VARCHAR(20) NOT NULL,
first VARCHAR(20) NOT NULL,
sex VARCHAR(6) NOT NULL,
dob DATE NOT NULL,
dod DATE DEFAULT NULL,
CHECK(id > 0 && id <= MaxPersonID(id) && dob < dod),
PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE Director(
id INT,
last VARCHAR(20) NOT NULL,
first VARCHAR(20) NOT NULL,
dob DATE NOT NULL,
dod DATE DEFAULT NULL,
CHECK(id > 0 && id <= MaxPersonID(id) && dob < dod),
PRIMARY KEY(id)) ENGINE=INNODB;

CREATE TABLE MovieGenre(
mid INT,
genre VARCHAR(20) NOT NULL,
FOREIGN KEY(mid) REFERENCES Movie(id)) ENGINE=INNODB;

CREATE TABLE MovieDirector(
mid INT NOT NULL,
did INT NOT NULL,
FOREIGN KEY(mid) REFERENCES Movie(id),
FOREIGN KEY(did) REFERENCES Director(id)) ENGINE=INNODB;

CREATE TABLE MovieActor(
mid INT NOT NULL,
aid INT NOT NULL,
role VARCHAR(50) NOT NULL,
FOREIGN KEY(mid) REFERENCES Movie(id),
FOREIGN KEY(aid) REFERENCES Actor(id)
) ENGINE=INNODB;

CREATE TABLE Review(
name VARCHAR(20) NOT NULL,
time TIMESTAMP,
mid INT NOT NULL,
rating INT NOT NULL,
comment VARCHAR(500) NOT NULL,
CHECK(rating>=0 && rating<=5),
FOREIGN KEY(mid) REFERENCES Movie(id)) ENGINE=INNODB;

CREATE TABLE MaxPersonID(
id INT
)ENGINE=INNODB;


CREATE TABLE MaxMovieID(
id INT
)ENGINE=INNODB;